service: kinesis-lambda-example
provider:
  name: aws
  runtime: ruby2.5
  memorySize: 128
functions:
  hello:
    handler: handler.hello
    events:
      - stream:
          arn: arn:aws:kinesis:#{AWS::Region}:#{AWS::AccountId}:stream/kinesis-lambda-example-stream
          batchSize: 100
          startingPosition: TRIM_HORIZON
          enabled: true
plugins:
  - serverless-ruby-package
  - serverless-pseudo-parameters
package:
  include:
    - handler.rb
